//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace SharePoint.Modernization.Scanner.Core.Workflow.SP2010 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class WorkflowInfo {
        
        private WorkflowInfoConditions conditionsField;
        
        private WorkflowInfoActions actionsField;
        
        private WorkflowInfoCompositeSteps compositeStepsField;
        
        private WorkflowInfoVariableTypes variableTypesField;
        
        private WorkflowInfoAssemblyRedirects assemblyRedirectsField;
        
        private WorkflowInfoCoercions coercionsField;
        
        private string languageField;
        
        /// <remarks/>
        public WorkflowInfoConditions Conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoActions Actions {
            get {
                return this.actionsField;
            }
            set {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoCompositeSteps CompositeSteps {
            get {
                return this.compositeStepsField;
            }
            set {
                this.compositeStepsField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoVariableTypes VariableTypes {
            get {
                return this.variableTypesField;
            }
            set {
                this.variableTypesField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoAssemblyRedirects AssemblyRedirects {
            get {
                return this.assemblyRedirectsField;
            }
            set {
                this.assemblyRedirectsField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoCoercions Coercions {
            get {
                return this.coercionsField;
            }
            set {
                this.coercionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoConditions {
        
        private WorkflowInfoConditionsDefault defaultField;
        
        private WorkflowInfoConditionsCondition[] conditionField;
        
        private string andField;
        
        private string orField;
        
        private string whenField;
        
        private string elseField;
        
        private string notField;
        
        /// <remarks/>
        public WorkflowInfoConditionsDefault Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Condition")]
        public WorkflowInfoConditionsCondition[] Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string And {
            get {
                return this.andField;
            }
            set {
                this.andField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Or {
            get {
                return this.orField;
            }
            set {
                this.orField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string When {
            get {
                return this.whenField;
            }
            set {
                this.whenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Else {
            get {
                return this.elseField;
            }
            set {
                this.elseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Not {
            get {
                return this.notField;
            }
            set {
                this.notField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoConditionsDefault {
        
        private ruleDesignerType ruleDesignerField;
        
        private WorkflowInfoConditionsDefaultItemKeyType itemKeyTypeField;
        
        public WorkflowInfoConditionsDefault() {
            this.itemKeyTypeField = WorkflowInfoConditionsDefaultItemKeyType.SystemInt32;
        }
        
        /// <remarks/>
        public ruleDesignerType RuleDesigner {
            get {
                return this.ruleDesignerField;
            }
            set {
                this.ruleDesignerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WorkflowInfoConditionsDefaultItemKeyType.SystemInt32)]
        public WorkflowInfoConditionsDefaultItemKeyType ItemKeyType {
            get {
                return this.itemKeyTypeField;
            }
            set {
                this.itemKeyTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ruleDesignerType {
        
        private ruleDesignerTypeFieldBind[] fieldBindField;
        
        private string sentenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FieldBind")]
        public ruleDesignerTypeFieldBind[] FieldBind {
            get {
                return this.fieldBindField;
            }
            set {
                this.fieldBindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sentence {
            get {
                return this.sentenceField;
            }
            set {
                this.sentenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ruleDesignerTypeFieldBind {
        
        private object[] itemsField;
        
        private string fieldField;
        
        private string textField;
        
        private string idField;
        
        private ruleDesignerTypeFieldBindDesignerType designerTypeField;
        
        private string operatorTypeFromField;
        
        private string typeFromField;
        
        private bool functionField;
        
        private string valueField;
        
        public ruleDesignerTypeFieldBind() {
            this.functionField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataSourceRef", typeof(ruleDesignerTypeFieldBindDataSourceRef))]
        [System.Xml.Serialization.XmlElementAttribute("Option", typeof(ruleDesignerTypeFieldBindOption))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ruleDesignerTypeFieldBindDesignerType DesignerType {
            get {
                return this.designerTypeField;
            }
            set {
                this.designerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OperatorTypeFrom {
            get {
                return this.operatorTypeFromField;
            }
            set {
                this.operatorTypeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeFrom {
            get {
                return this.typeFromField;
            }
            set {
                this.typeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ruleDesignerTypeFieldBindDataSourceRef {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataSourceType {
        
        private dataSourceTypeSchemaSource schemaSourceField;
        
        private dataSourceTypeEvaluation evaluationField;
        
        private string internalNameField;
        
        private string nameField;
        
        private string namePropertyField;
        
        /// <remarks/>
        public dataSourceTypeSchemaSource SchemaSource {
            get {
                return this.schemaSourceField;
            }
            set {
                this.schemaSourceField = value;
            }
        }
        
        /// <remarks/>
        public dataSourceTypeEvaluation Evaluation {
            get {
                return this.evaluationField;
            }
            set {
                this.evaluationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InternalName {
            get {
                return this.internalNameField;
            }
            set {
                this.internalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameProperty {
            get {
                return this.namePropertyField;
            }
            set {
                this.namePropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeSchemaSource {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType", typeof(dataSourceTypeSchemaSourceContentType))]
        [System.Xml.Serialization.XmlElementAttribute("Dictionary", typeof(dataSourceTypeSchemaSourceDictionary))]
        [System.Xml.Serialization.XmlElementAttribute("Fields", typeof(dataSourceTypeSchemaSourceFields))]
        [System.Xml.Serialization.XmlElementAttribute("NestedInitiationFieldNodes", typeof(object))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeSchemaSourceContentType {
        
        private string iDFromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IDFrom {
            get {
                return this.iDFromField;
            }
            set {
                this.iDFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeSchemaSourceDictionary {
        
        private string valueFromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ValueFrom {
            get {
                return this.valueFromField;
            }
            set {
                this.valueFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeSchemaSourceFields {
        
        private dataSourceTypeSchemaSourceFieldsField[] fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public dataSourceTypeSchemaSourceFieldsField[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeSchemaSourceFieldsField {
        
        private dataSourceTypeSchemaSourceFieldsFieldCHOICE[] cHOICESField;
        
        private string nameField;
        
        private string displayNameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CHOICE", IsNullable=false)]
        public dataSourceTypeSchemaSourceFieldsFieldCHOICE[] CHOICES {
            get {
                return this.cHOICESField;
            }
            set {
                this.cHOICESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeSchemaSourceFieldsFieldCHOICE {
        
        private string displayNameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeEvaluation {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivitySource", typeof(dataSourceTypeEvaluationActivitySource))]
        [System.Xml.Serialization.XmlElementAttribute("HashtableSource", typeof(dataSourceTypeEvaluationHashtableSource))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeEvaluationActivitySource {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class dataSourceTypeEvaluationHashtableSource {
        
        private string hashtableFromField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HashtableFrom {
            get {
                return this.hashtableFromField;
            }
            set {
                this.hashtableFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class defaultElementType {
        
        private ruleDesignerType ruleDesignerField;
        
        /// <remarks/>
        public ruleDesignerType RuleDesigner {
            get {
                return this.ruleDesignerField;
            }
            set {
                this.ruleDesignerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ruleDesignerTypeFieldBindOption {
        
        private string nameField;
        
        private string valueField;
        
        private string typeFilterField;
        
        private string unaryHidesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeFilter {
            get {
                return this.typeFilterField;
            }
            set {
                this.typeFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnaryHides {
            get {
                return this.unaryHidesField;
            }
            set {
                this.unaryHidesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum ruleDesignerTypeFieldBindDesignerType {
        
        /// <remarks/>
        AddPermission,
        
        /// <remarks/>
        Assignment,
        
        /// <remarks/>
        Bool,
        
        /// <remarks/>
        CheckPermission,
        
        /// <remarks/>
        ChooseDoclibItem,
        
        /// <remarks/>
        ChooseListItem,
        
        /// <remarks/>
        CreateListItem,
        
        /// <remarks/>
        DataSourceFieldNames,
        
        /// <remarks/>
        DataSourceValues,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Dependent,
        
        /// <remarks/>
        Dropdown,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        FieldNames,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Hyperlink,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        ListNames,
        
        /// <remarks/>
        Operator,
        
        /// <remarks/>
        ParameterNames,
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        RemovePermission,
        
        /// <remarks/>
        ReplacePermission,
        
        /// <remarks/>
        SinglePerson,
        
        /// <remarks/>
        StatusDropdown,
        
        /// <remarks/>
        StringBuilder,
        
        /// <remarks/>
        Survey,
        
        /// <remarks/>
        TaskSummary,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        TextBox,
        
        /// <remarks/>
        TextArea,
        
        /// <remarks/>
        UpdateListItem,
        
        /// <remarks/>
        WritableFieldNames,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum WorkflowInfoConditionsDefaultItemKeyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int32")]
        SystemInt32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Microsoft.SharePoint.Workflow.SPItemKey")]
        MicrosoftSharePointWorkflowSPItemKey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoConditionsCondition {
        
        private ruleDesignerType ruleDesignerField;
        
        private parametersTypeParameter[] parametersField;
        
        private WorkflowInfoConditionsConditionType typeField;
        
        private bool typeFieldSpecified;
        
        private string nameField;
        
        private appliesToTypes appliesToField;
        
        private bool usesCurrentItemField;
        
        private WorkflowInfoConditionsConditionItemKeyType itemKeyTypeField;
        
        private string functionNameField;
        
        private string assemblyField;
        
        private string classNameField;
        
        private string requiredInvocationTagsField;
        
        private string invocationTagsField;
        
        private string prohibitedInvocationTagsField;
        
        private string prohibitedDirectParentInvocationTagsField;
        
        public WorkflowInfoConditionsCondition() {
            this.usesCurrentItemField = false;
            this.itemKeyTypeField = WorkflowInfoConditionsConditionItemKeyType.SystemInt32;
        }
        
        /// <remarks/>
        public ruleDesignerType RuleDesigner {
            get {
                return this.ruleDesignerField;
            }
            set {
                this.ruleDesignerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public parametersTypeParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WorkflowInfoConditionsConditionType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public appliesToTypes AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UsesCurrentItem {
            get {
                return this.usesCurrentItemField;
            }
            set {
                this.usesCurrentItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(WorkflowInfoConditionsConditionItemKeyType.SystemInt32)]
        public WorkflowInfoConditionsConditionItemKeyType ItemKeyType {
            get {
                return this.itemKeyTypeField;
            }
            set {
                this.itemKeyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FunctionName {
            get {
                return this.functionNameField;
            }
            set {
                this.functionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequiredInvocationTags {
            get {
                return this.requiredInvocationTagsField;
            }
            set {
                this.requiredInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InvocationTags {
            get {
                return this.invocationTagsField;
            }
            set {
                this.invocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProhibitedInvocationTags {
            get {
                return this.prohibitedInvocationTagsField;
            }
            set {
                this.prohibitedInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProhibitedDirectParentInvocationTags {
            get {
                return this.prohibitedDirectParentInvocationTagsField;
            }
            set {
                this.prohibitedDirectParentInvocationTagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class parametersTypeParameter {
        
        private string nameField;
        
        private string typeField;
        
        private parametersTypeParameterDirection directionField;
        
        private string descriptionField;
        
        private parametersTypeParameterDesignerType designerTypeField;
        
        private bool designerTypeFieldSpecified;
        
        private bool showLookupForDropdownField;
        
        private string displayNameField;
        
        private string initialValueField;
        
        private string initialBindingField;
        
        public parametersTypeParameter() {
            this.showLookupForDropdownField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public parametersTypeParameterDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public parametersTypeParameterDesignerType DesignerType {
            get {
                return this.designerTypeField;
            }
            set {
                this.designerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DesignerTypeSpecified {
            get {
                return this.designerTypeFieldSpecified;
            }
            set {
                this.designerTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowLookupForDropdown {
            get {
                return this.showLookupForDropdownField;
            }
            set {
                this.showLookupForDropdownField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InitialValue {
            get {
                return this.initialValueField;
            }
            set {
                this.initialValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InitialBinding {
            get {
                return this.initialBindingField;
            }
            set {
                this.initialBindingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum parametersTypeParameterDirection {
        
        /// <remarks/>
        In,
        
        /// <remarks/>
        Out,
        
        /// <remarks/>
        Optional,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum parametersTypeParameterDesignerType {
        
        /// <remarks/>
        ContentType,
        
        /// <remarks/>
        DataSourceFieldNames,
        
        /// <remarks/>
        DataSourceValues,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Dependent,
        
        /// <remarks/>
        Dropdown,
        
        /// <remarks/>
        FieldNames,
        
        /// <remarks/>
        Hide,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        ItemProperties,
        
        /// <remarks/>
        ListItem,
        
        /// <remarks/>
        ListNames,
        
        /// <remarks/>
        ParameterNames,
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        SinglePerson,
        
        /// <remarks/>
        StatusDropdown,
        
        /// <remarks/>
        StringBuilder,
        
        /// <remarks/>
        TextArea,
        
        /// <remarks/>
        TextBox,
        
        /// <remarks/>
        WritableFieldNames,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum WorkflowInfoConditionsConditionType {
        
        /// <remarks/>
        Advanced,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    public enum appliesToTypes {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        list,
        
        /// <remarks/>
        doclib,
        
        /// <remarks/>
        all,
        
        /// <remarks/>
        displayonly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum WorkflowInfoConditionsConditionItemKeyType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int32")]
        SystemInt32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Microsoft.SharePoint.Workflow.SPItemKey")]
        MicrosoftSharePointWorkflowSPItemKey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoActions {
        
        private defaultElementType defaultField;
        
        private WorkflowInfoActionsAction[] actionField;
        
        private string sequentialField;
        
        private string parallelField;
        
        /// <remarks/>
        public defaultElementType Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Action")]
        public WorkflowInfoActionsAction[] Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sequential {
            get {
                return this.sequentialField;
            }
            set {
                this.sequentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Parallel {
            get {
                return this.parallelField;
            }
            set {
                this.parallelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoActionsAction {
        
        private parametersTypeParameter[] parametersField;
        
        private ruleDesignerType ruleDesignerField;
        
        private dataSourceType[] dataSourcesField;
        
        private WorkflowInfoActionsActionModification[] modificationsField;
        
        private WorkflowInfoActionsActionActionVariables actionVariablesField;
        
        private WorkflowInfoActionsActionActionBody actionBodyField;
        
        private WorkflowInfoActionsActionActionConditions actionConditionsField;
        
        private string nameField;
        
        private string classNameField;
        
        private string assemblyField;
        
        private string functionNameField;
        
        private string categoryField;
        
        private bool createsTaskField;
        
        private string createsInListField;
        
        private appliesToTypes appliesToField;
        
        private bool isErrorField;
        
        private bool listModerationField;
        
        private bool usesCurrentItemField;
        
        private string requiredInvocationTagsField;
        
        private string invocationTagsField;
        
        private string prohibitedInvocationTagsField;
        
        private string prohibitedDirectParentInvocationTagsField;
        
        private WorkflowInfoActionsActionCreatedTaskFormType createdTaskFormTypeField;
        
        private bool createdTaskFormTypeFieldSpecified;
        
        private string @__SolutionIdField;
        
        private bool sandboxedFunctionField;
        
        public WorkflowInfoActionsAction() {
            this.functionNameField = "";
            this.createsTaskField = false;
            this.isErrorField = false;
            this.listModerationField = false;
            this.usesCurrentItemField = false;
            this.sandboxedFunctionField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public parametersTypeParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        public ruleDesignerType RuleDesigner {
            get {
                return this.ruleDesignerField;
            }
            set {
                this.ruleDesignerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DataSource", IsNullable=false)]
        public dataSourceType[] DataSources {
            get {
                return this.dataSourcesField;
            }
            set {
                this.dataSourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Modification", IsNullable=false)]
        public WorkflowInfoActionsActionModification[] Modifications {
            get {
                return this.modificationsField;
            }
            set {
                this.modificationsField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoActionsActionActionVariables ActionVariables {
            get {
                return this.actionVariablesField;
            }
            set {
                this.actionVariablesField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoActionsActionActionBody ActionBody {
            get {
                return this.actionBodyField;
            }
            set {
                this.actionBodyField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowInfoActionsActionActionConditions ActionConditions {
            get {
                return this.actionConditionsField;
            }
            set {
                this.actionConditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string FunctionName {
            get {
                return this.functionNameField;
            }
            set {
                this.functionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CreatesTask {
            get {
                return this.createsTaskField;
            }
            set {
                this.createsTaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CreatesInList {
            get {
                return this.createsInListField;
            }
            set {
                this.createsInListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public appliesToTypes AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ListModeration {
            get {
                return this.listModerationField;
            }
            set {
                this.listModerationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool UsesCurrentItem {
            get {
                return this.usesCurrentItemField;
            }
            set {
                this.usesCurrentItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequiredInvocationTags {
            get {
                return this.requiredInvocationTagsField;
            }
            set {
                this.requiredInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InvocationTags {
            get {
                return this.invocationTagsField;
            }
            set {
                this.invocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProhibitedInvocationTags {
            get {
                return this.prohibitedInvocationTagsField;
            }
            set {
                this.prohibitedInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProhibitedDirectParentInvocationTags {
            get {
                return this.prohibitedDirectParentInvocationTagsField;
            }
            set {
                this.prohibitedDirectParentInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public WorkflowInfoActionsActionCreatedTaskFormType CreatedTaskFormType {
            get {
                return this.createdTaskFormTypeField;
            }
            set {
                this.createdTaskFormTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreatedTaskFormTypeSpecified {
            get {
                return this.createdTaskFormTypeFieldSpecified;
            }
            set {
                this.createdTaskFormTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @__SolutionId {
            get {
                return this.@__SolutionIdField;
            }
            set {
                this.@__SolutionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SandboxedFunction {
            get {
                return this.sandboxedFunctionField;
            }
            set {
                this.sandboxedFunctionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoActionsActionModification {
        
        private string typeIdField;
        
        private string nameFormatField;
        
        private string formURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameFormat {
            get {
                return this.nameFormatField;
            }
            set {
                this.nameFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FormURN {
            get {
                return this.formURNField;
            }
            set {
                this.formURNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoActionsActionActionVariables {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoActionsActionActionBody {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoActionsActionActionConditions {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum WorkflowInfoActionsActionCreatedTaskFormType {
        
        /// <remarks/>
        DataCollectTask,
        
        /// <remarks/>
        GroupAssignedTask,
        
        /// <remarks/>
        TodoItemTask,
        
        /// <remarks/>
        TaskProcess,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoCompositeSteps {
        
        private WorkflowInfoCompositeStepsCompositeStep[] compositeStepField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompositeStep")]
        public WorkflowInfoCompositeStepsCompositeStep[] CompositeStep {
            get {
                return this.compositeStepField;
            }
            set {
                this.compositeStepField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoCompositeStepsCompositeStep {
        
        private dataSourceType[] dataSourcesField;
        
        private string nameField;
        
        private string classNameField;
        
        private string assemblyField;
        
        private appliesToTypes appliesToField;
        
        private string requiredInvocationTagsField;
        
        private string invocationTagsField;
        
        private string prohibitedInvocationTagsField;
        
        private string prohibitedDirectParentInvocationTagsField;
        
        private string orderField;
        
        private string descriptionField;
        
        public WorkflowInfoCompositeStepsCompositeStep() {
            this.orderField = "0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DataSource", IsNullable=false)]
        public dataSourceType[] DataSources {
            get {
                return this.dataSourcesField;
            }
            set {
                this.dataSourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public appliesToTypes AppliesTo {
            get {
                return this.appliesToField;
            }
            set {
                this.appliesToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RequiredInvocationTags {
            get {
                return this.requiredInvocationTagsField;
            }
            set {
                this.requiredInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string InvocationTags {
            get {
                return this.invocationTagsField;
            }
            set {
                this.invocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProhibitedInvocationTags {
            get {
                return this.prohibitedInvocationTagsField;
            }
            set {
                this.prohibitedInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProhibitedDirectParentInvocationTags {
            get {
                return this.prohibitedDirectParentInvocationTagsField;
            }
            set {
                this.prohibitedDirectParentInvocationTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoVariableTypes {
        
        private WorkflowInfoVariableTypesVariableType[] variableTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VariableType")]
        public WorkflowInfoVariableTypesVariableType[] VariableType {
            get {
                return this.variableTypeField;
            }
            set {
                this.variableTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoVariableTypesVariableType {
        
        private string typeField;
        
        private string displayNameField;
        
        private string assemblyField;
        
        private string coercionActivityField;
        
        private bool defaultField;
        
        private bool itemIdTypeField;
        
        private bool hiddenField;
        
        public WorkflowInfoVariableTypesVariableType() {
            this.defaultField = false;
            this.itemIdTypeField = false;
            this.hiddenField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CoercionActivity {
            get {
                return this.coercionActivityField;
            }
            set {
                this.coercionActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ItemIdType {
            get {
                return this.itemIdTypeField;
            }
            set {
                this.itemIdTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoAssemblyRedirects {
        
        private WorkflowInfoAssemblyRedirectsAssemblyRedirect[] assemblyRedirectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssemblyRedirect")]
        public WorkflowInfoAssemblyRedirectsAssemblyRedirect[] AssemblyRedirect {
            get {
                return this.assemblyRedirectField;
            }
            set {
                this.assemblyRedirectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoAssemblyRedirectsAssemblyRedirect {
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoCoercions {
        
        private WorkflowInfoCoercionsCoercion[] coercionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Coercion")]
        public WorkflowInfoCoercionsCoercion[] Coercion {
            get {
                return this.coercionField;
            }
            set {
                this.coercionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WorkflowInfoCoercionsCoercion {
        
        private string nameField;
        
        private string assemblyField;
        
        private string displayNameField;
        
        private bool catchAllField;
        
        private string rankDefaultField;
        
        private string sourceTypeField;
        
        private string sourceFieldTypeField;
        
        private string destinationTypeField;
        
        private string destinationFieldTypeField;
        
        private string classNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Assembly {
            get {
                return this.assemblyField;
            }
            set {
                this.assemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool CatchAll {
            get {
                return this.catchAllField;
            }
            set {
                this.catchAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string RankDefault {
            get {
                return this.rankDefaultField;
            }
            set {
                this.rankDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceFieldType {
            get {
                return this.sourceFieldTypeField;
            }
            set {
                this.sourceFieldTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestinationType {
            get {
                return this.destinationTypeField;
            }
            set {
                this.destinationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DestinationFieldType {
            get {
                return this.destinationFieldTypeField;
            }
            set {
                this.destinationFieldTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
    }
}
